print("hola git") 
print("segunda linea") 
print("cambios por interfaz")
print("from feature branch")
print("second commit from feature branch") 
print ("this is the change in main")
print ("create a change to create conflict")
